spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qwp0518/Configuration
          default-label: master
          username: qwp0518
          password: Qwp@qwp@0407
  application:
    name: config-server
server:
  port: 8769
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/