zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    user-service:
      path: /userapi/**
      serviceId: user-service
      sensitiveHeaders:
    blog-service:
      path: /blogapi/**
      serviceId: blog-service
      sensitiveHeaders:
server:
  port: 5000
